#ifndef GUARD_CONSTANTS_MAP_EVENT_IDS_H
#define GUARD_CONSTANTS_MAP_EVENT_IDS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/*/map.json
//

// MAP_AQUA_HIDEOUT_B2F
#define LOCALID_AQUA_HIDEOUT_MATT 1
#define LOCALID_AQUA_HIDEOUT_SUBMARINE 4

// MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM
#define LOCALID_ARENA_BATTLE_BLACK_BELT_1 1
#define LOCALID_ARENA_BATTLE_BLACK_BELT_2 2
#define LOCALID_ARENA_BATTLE_BLACK_BELT_3 3
#define LOCALID_ARENA_BATTLE_BLACK_BELT_4 4
#define LOCALID_ARENA_BATTLE_ATTENDANT 5
#define LOCALID_ARENA_BATTLE_OPPONENT 7
#define LOCALID_ARENA_BATTLE_PLAYER 8
#define LOCALID_ARENA_BATTLE_ANNOUNCER 9

// MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR
#define LOCALID_ARENA_CORRIDOR_ATTENDANT 1

// MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY
#define LOCALID_ARENA_ATTENDANT 1

// MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM
#define LOCALID_DOME_ANNOUNCER 1
#define LOCALID_DOME_AUDIENCE_TWIN 2
#define LOCALID_DOME_AUDIENCE_WALKING 6
#define LOCALID_DOME_REFEREE 9
#define LOCALID_DOME_PLAYER 13
#define LOCALID_DOME_OPPONENT 15

// MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR
#define LOCALID_DOME_CORRIDOR_ATTENDANT 1

// MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY
#define LOCALID_DOME_ATTENDANT_SINGLES 1
#define LOCALID_DOME_ATTENDANT_DOUBLES 6

// MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM
#define LOCALID_DOME_PRE_BATTLE_ATTENDANT 1

// MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM
#define LOCALID_FACTORY_BATTLE_SCIENTIST_1 1
#define LOCALID_FACTORY_BATTLE_OPPONENT 2
#define LOCALID_FACTORY_BATTLE_SCIENTIST_2 3
#define LOCALID_FACTORY_BATTLE_SCIENTIST_3 4
#define LOCALID_FACTORY_BATTLE_SCIENTIST_4 5
#define LOCALID_FACTORY_BATTLE_SCIENTIST_5 6
#define LOCALID_FACTORY_BATTLE_SCIENTIST_6 7
#define LOCALID_FACTORY_BATTLE_PLAYER 8

// MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY
#define LOCALID_FACTORY_ATTENDANT_SINGLES 1
#define LOCALID_FACTORY_ATTENDANT_DOUBLES 6

// MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM
#define LOCALID_FACTORY_PRE_BATTLE_ATTENDANT 1

// MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM
#define LOCALID_PALACE_BATTLE_PLAYER 1
#define LOCALID_PALACE_BATTLE_OPPONENT 2
#define LOCALID_PALACE_BATTLE_ATTENDANT 3
#define LOCALID_PALACE_DUSCLOPS 4
#define LOCALID_PALACE_AZURILL 5

// MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR
#define LOCALID_PALACE_CORRIDOR_ATTENDANT 1

// MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY
#define LOCALID_PALACE_ATTENDANT_SINGLES 1
#define LOCALID_PALACE_ATTENDANT_DOUBLES 6

// MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR
#define LOCALID_PIKE_CORRIDOR_ATTENDANT 1

// MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY
#define LOCALID_PIKE_LOBBY_ATTENDANT 1

// MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL
#define LOCALID_PIKE_FINAL_ROOM_ATTENDANT 1

// MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL
#define LOCALID_PIKE_ROOM_NPC_1 1
#define LOCALID_PIKE_ROOM_NPC_2 2

// MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM
#define LOCALID_PIKE_HINT_GIVER 2

// MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY
#define LOCALID_PYRAMID_LOBBY_ATTENDANT 1
#define LOCALID_PYRAMID_LOBBY_HINT_GIVER 2

// MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP
#define LOCALID_PYRAMID_TOP_ATTENDANT 1
#define LOCALID_BRANDON 2

// MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM
#define LOCALID_TOWER_BATTLE_OPPONENT 1
#define LOCALID_TOWER_BATTLE_ATTENDANT_1 2
#define LOCALID_TOWER_BATTLE_ATTENDANT_2 3

// MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR
#define LOCALID_TOWER_CORRIDOR_ATTENDANT 1

// MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR
#define LOCALID_TOWER_ELEVATOR_ATTENDANT 1

// MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY
#define LOCALID_TOWER_ATTENDANT_SINGLES 1
#define LOCALID_TOWER_LOBBY_REPORTER 5
#define LOCALID_APPRENTICE 6
#define LOCALID_TOWER_ATTENDANT_DOUBLES 7
#define LOCALID_TOWER_ATTENDANT_MULTIS 8
#define LOCALID_TOWER_ATTENDANT_LINK_MULTIS 9

// MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM
#define LOCALID_TOWER_MULTI_BATTLE_OPPONENT_1 1
#define LOCALID_TOWER_MULTI_BATTLE_ATTENDANT_1 2
#define LOCALID_TOWER_MULTI_BATTLE_ATTENDANT_2 3
#define LOCALID_TOWER_MULTI_BATTLE_OPPONENT_2 4
#define LOCALID_TOWER_MULTI_BATTLE_PLAYER 5
#define LOCALID_TOWER_MULTI_BATTLE_PARTNER 6

// MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR
#define LOCALID_TOWER_MULTI_CORRIDOR_PLAYER 1
#define LOCALID_TOWER_MULTI_CORRIDOR_ATTENDANT_1 2
#define LOCALID_TOWER_MULTI_CORRIDOR_ATTENDANT_2 3
#define LOCALID_TOWER_MULTI_CORRIDOR_PARTNER 4

// MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM
#define LOCALID_TOWER_PARTNER_ROOM_ATTENDANT 1

// MAP_BATTLE_FRONTIER_MART
#define LOCALID_FRONTIER_MART_CLERK 1
#define LOCALID_FRONTIER_MART_OLD_WOMAN 2

// MAP_BATTLE_FRONTIER_OUTSIDE_EAST
#define LOCALID_FRONTIER_SUDOWOODO 14

// MAP_BATTLE_FRONTIER_OUTSIDE_WEST
#define LOCALID_FRONTIER_SS_TIDAL 2
#define LOCALID_FRONTIER_FERRY_ATTENDANT 3
#define LOCALID_FRONTIER_MANIAC_1 9
#define LOCALID_FRONTIER_MANIAC_2 10
#define LOCALID_FRONTIER_GIRL 12
#define LOCALID_FRONTIER_CAMPER 14
#define LOCALID_FRONTIER_FISHERMAN_2 18
#define LOCALID_FRONTIER_MAN_4 23

// MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F
#define LOCALID_FRONTIER_NURSE 1

// MAP_BATTLE_FRONTIER_RECEPTION_GATE
#define LOCALID_FRONTIER_RECEPTION_GREETER 1
#define LOCALID_FRONTIER_RECEPTION_GUIDE 2
#define LOCALID_FRONTIER_RECEPTION_SCOTT 4

// MAP_BATTLE_FRONTIER_SCOTTS_HOUSE
#define LOCALID_SCOTTS_HOUSE_SCOTT 1

// MAP_BIRTH_ISLAND_EXTERIOR
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 1
#define LOCALID_BIRTH_ISLAND_DEOXYS 2

// MAP_BIRTH_ISLAND_HARBOR
#define LOCALID_BIRTH_ISLAND_SAILOR 1
#define LOCALID_BIRTH_ISLAND_SS_TIDAL 2

// MAP_CAVE_OF_ORIGIN_B1F
#define LOCALID_CAVE_OF_ORIGIN_WALLACE 1

// MAP_CONTEST_HALL
#define LOCALID_CONTEST_MC 1
#define LOCALID_CONTEST_JUDGE 2
#define LOCALID_CONTESTANT_1 3
#define LOCALID_CONTESTANT_2 4
#define LOCALID_CONTESTANT_3 5
#define LOCALID_CONTEST_AUDIENCE_1 6
#define LOCALID_CONTEST_AUDIENCE_3 7
#define LOCALID_CONTEST_AUDIENCE_4 8
#define LOCALID_CONTEST_AUDIENCE_5 9
#define LOCALID_CONTEST_AUDIENCE_6 10
#define LOCALID_CONTEST_AUDIENCE_7 11
#define LOCALID_CONTEST_AUDIENCE_2 12
#define LOCALID_CONTEST_POKEBALL 13
#define LOCALID_CONTESTANT_4 14
#define LOCALID_CONTEST_ARTIST 15

// MAP_DESERT_UNDERPASS
#define LOCALID_UNDERPASS_FOSSIL 1

// MAP_DEWFORD_TOWN
#define LOCALID_DEWFORD_BRINEY 2
#define LOCALID_DEWFORD_BOAT 4

// MAP_DEWFORD_TOWN_HALL
#define LOCALID_DEWFORD_HALL_EXPERT_M 4
#define LOCALID_DEWFORD_HALL_TWIN 5
#define LOCALID_DEWFORD_HALL_SCHOOL_KID_M 7
#define LOCALID_DEWFORD_HALL_PSYCHIC_M 8

// MAP_DEWFORD_TOWN_POKEMON_CENTER_1F
#define LOCALID_DEWFORD_NURSE 1

// MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM
#define LOCALID_CHAMPIONS_ROOM_WALLACE 1
#define LOCALID_CHAMPIONS_ROOM_RIVAL 2
#define LOCALID_CHAMPIONS_ROOM_BIRCH 3

// MAP_EVER_GRANDE_CITY_HALL_OF_FAME
#define LOCALID_HALL_OF_FAME_WALLACE 1

// MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F
#define LOCALID_EVER_GRANDE_NURSE 1
#define LOCALID_EVER_GRANDE_SCOTT 4

// MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F
#define LOCALID_LEAGUE_NURSE 1
#define LOCALID_LEAGUE_GUARD_1 3
#define LOCALID_LEAGUE_GUARD_2 4

// MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM
#define LOCALID_FALLARBOR_TENT_BATTLE_PLAYER 1
#define LOCALID_FALLARBOR_TENT_BATTLE_ATTENDANT 2
#define LOCALID_FALLARBOR_TENT_BATTLE_OPPONENT 3

// MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR
#define LOCALID_FALLARBOR_TENT_CORRIDOR_ATTENDANT 1

// MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY
#define LOCALID_FALLARBOR_TENT_ATTENDANT 1

// MAP_FALLARBOR_TOWN_MART
#define LOCALID_FALLARBOR_MART_CLERK 1

// MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE
#define LOCALID_MOVE_RELEARNER 1

// MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F
#define LOCALID_FALLARBOR_NURSE 1
#define LOCALID_FALLARBOR_LANETTE 4

// MAP_FARAWAY_ISLAND_ENTRANCE
#define LOCALID_FARAWAY_ISLAND_SAILOR 1
#define LOCALID_FARAWAY_ISLAND_SS_TIDAL 2

// MAP_FARAWAY_ISLAND_INTERIOR
#define LOCALID_FARAWAY_ISLAND_MEW 1

// MAP_FORTREE_CITY_HOUSE4
#define LOCALID_FORTREE_HOUSE_WINGULL 3

// MAP_FORTREE_CITY_MART
#define LOCALID_FORTREE_MART_CLERK 1

// MAP_FORTREE_CITY_POKEMON_CENTER_1F
#define LOCALID_FORTREE_NURSE 1

// MAP_GRANITE_CAVE_STEVENS_ROOM
#define LOCALID_GRANITE_CAVE_STEVEN 1

// MAP_INSIDE_OF_TRUCK
#define LOCALID_TRUCK_BOX_TOP 1
#define LOCALID_TRUCK_BOX_BOTTOM_L 2
#define LOCALID_TRUCK_BOX_BOTTOM_R 3

// MAP_JAGGED_PASS
#define LOCALID_MAGMA_HIDEOUT_GUARD 5

// MAP_KAURI_WOODS
#define LOCALID_PETALBURG_WOODS_GRUNT 3
#define LOCALID_PETALBURG_WOODS_DEVON_EMPLOYEE 4

// MAP_KAWAKAWA_INLET_MCHOUSE_1F
#define LOCALID_PLAYERS_HOUSE_1F_MOM 1

// MAP_LAVARIDGE_TOWN
#define LOCALID_LAVARIDGE_RIVAL_ON_BIKE 7
#define LOCALID_LAVARIDGE_RIVAL 8

// MAP_LAVARIDGE_TOWN_GYM_1F
#define LOCALID_COLE 2
#define LOCALID_GERALD 3
#define LOCALID_AXLE 4
#define LOCALID_DANIELLE 5

// MAP_LAVARIDGE_TOWN_GYM_B1F
#define LOCALID_JACE 1
#define LOCALID_KEEGAN 2
#define LOCALID_JEFF 3
#define LOCALID_ELI 4

// MAP_LAVARIDGE_TOWN_MART
#define LOCALID_LAVARIDGE_MART_CLERK 1

// MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F
#define LOCALID_LAVARIDGE_NURSE 1

// MAP_LILYCOVE_CITY
#define LOCALID_LILYCOVE_WOMAN_1 19
#define LOCALID_LILYCOVE_MAN_1 20

// MAP_LILYCOVE_CITY_CONTEST_HALL
#define LOCALID_SMART_MC 4
#define LOCALID_SMART_JUDGE 5
#define LOCALID_SMART_CONTESTANT_1 6
#define LOCALID_SMART_CONTESTANT_2 7
#define LOCALID_SMART_CONTESTANT_3 8
#define LOCALID_SMART_CONTESTANT_4 9
#define LOCALID_SMART_AUDIENCE_4 11
#define LOCALID_SMART_AUDIENCE_2 12
#define LOCALID_BEAUTY_MC 13
#define LOCALID_BEAUTY_JUDGE 14
#define LOCALID_BEAUTY_CONTESTANT_1 15
#define LOCALID_BEAUTY_CONTESTANT_2 16
#define LOCALID_BEAUTY_CONTESTANT_3 17
#define LOCALID_BEAUTY_CONTESTANT_4 18
#define LOCALID_BEAUTY_AUDIENCE_1 19
#define LOCALID_BEAUTY_AUDIENCE_3 20
#define LOCALID_BEAUTY_AUDIENCE_2 21
#define LOCALID_SMART_AUDIENCE_3 22
#define LOCALID_CUTE_MC 23
#define LOCALID_CUTE_JUDGE 24
#define LOCALID_CUTE_CONTESTANT_1 25
#define LOCALID_CUTE_CONTESTANT_2 26
#define LOCALID_CUTE_CONTESTANT_3 27
#define LOCALID_CUTE_CONTESTANT_4 28
#define LOCALID_CUTE_AUDIENCE_1 29
#define LOCALID_CUTE_AUDIENCE_3 30
#define LOCALID_CUTE_AUDIENCE_2 31

// MAP_LILYCOVE_CITY_CONTEST_LOBBY
#define LOCALID_CONTEST_LOBBY_RECEPTIONIST 1
#define LOCALID_CONTEST_LOBBY_LINK_RECEPTIONIST 2
#define LOCALID_CONTEST_LOBBY_BLENDER_2_LEADER 3
#define LOCALID_CONTEST_LOBBY_ARTIST 4
#define LOCALID_CONTEST_LOBBY_BLENDER_3_PARTICIPANT_1 9
#define LOCALID_CONTEST_LOBBY_BLENDER_2_PARTICIPANT 10
#define LOCALID_CONTEST_LOBBY_LINK_ARTIST 11
#define LOCALID_CONTEST_LOBBY_BLENDER_3_LEADER 15
#define LOCALID_BLEND_MASTER 16
#define LOCALID_CONTEST_LOBBY_BLENDER_3_PARTICIPANT_2 17

// MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F
#define LOCALID_MOTEL_OWNER 1

// MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F
#define LOCALID_LOTTERY_CLERK 2

// MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F
#define LOCALID_DEPARTMENT_STORE_STAIRS_WOMAN 7

// MAP_LILYCOVE_CITY_HARBOR
#define LOCALID_LILYCOVE_HARBOR_ATTENDANT 1
#define LOCALID_LILYCOVE_HARBOR_SS_TIDAL 2
#define LOCALID_LILYCOVE_HARBOR_FERRY_SAILOR 4
#define LOCALID_LILYCOVE_HARBOR_BRINEY 5

// MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F
#define LOCALID_MUSEUM_1F_CURATOR 2
#define LOCALID_MUSEUM_1F_ARTIST_2 8

// MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F
#define LOCALID_MUSEUM_2F_CURATOR 1

// MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE
#define LOCALID_MOVE_DELETER 1

// MAP_LILYCOVE_CITY_POKEMON_CENTER_1F
#define LOCALID_LILYCOVE_NURSE 1
#define LOCALID_LILYCOVE_LADY 4
#define LOCALID_LILYCOVE_LADYS_MON 5

// MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB
#define LOCALID_TRAINER_FAN_CLUB_LASS 1
#define LOCALID_TRAINER_FAN_CLUB_MAN 2
#define LOCALID_TRAINER_FAN_CLUB_POKEFAN_M 3
#define LOCALID_TRAINER_FAN_CLUB_LITTLE_GIRL 4
#define LOCALID_TRAINER_FAN_CLUB_NINJA_BOY 5
#define LOCALID_TRAINER_FAN_CLUB_BOY 6
#define LOCALID_TRAINER_FAN_CLUB_WOMAN 7
#define LOCALID_TRAINER_FAN_CLUB_EXPERT_F 8

// MAP_LITTLEROOT_TOWN
#define LOCALID_LITTLEROOT_TWIN 1
#define LOCALID_LITTLEROOT_MOM 4
#define LOCALID_LITTLEROOT_RIVAL 7
#define LOCALID_LITTLEROOT_BIRCH 8

// MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F
#define LOCALID_PLAYERS_HOUSE_1F_MOM 1
#define LOCALID_RIVALS_HOUSE_1F_MOM 4
#define LOCALID_PLAYERS_HOUSE_1F_DAD 5
#define LOCALID_RIVALS_HOUSE_1F_RIVAL 7

// MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F
#define LOCALID_RIVALS_HOUSE_2F_RIVAL 1
#define LOCALID_PLAYERS_HOUSE_2F_MOM 14

// MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F
#define LOCALID_PLAYERS_HOUSE_1F_MOM 1
#define LOCALID_RIVALS_HOUSE_1F_MOM 4
#define LOCALID_PLAYERS_HOUSE_1F_DAD 5
#define LOCALID_RIVALS_HOUSE_1F_RIVAL 7

// MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F
#define LOCALID_RIVALS_HOUSE_2F_RIVAL 1
#define LOCALID_PLAYERS_HOUSE_2F_MOM 14

// MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB
#define LOCALID_BIRCHS_LAB_AIDE 1
#define LOCALID_BIRCHS_LAB_BIRCH 2
#define LOCALID_BIRCHS_LAB_RIVAL 3
#define LOCALID_BIRCHS_LAB_CYNDAQUIL_BALL 4
#define LOCALID_BIRCHS_LAB_TOTODILE_BALL 5
#define LOCALID_BIRCHS_LAB_CHIKORITA_BALL 6

// MAP_MAGMA_HIDEOUT_4F
#define LOCALID_MAGMA_HIDEOUT_4F_GROUDON 1
#define LOCALID_MAGMA_HIDEOUT_4F_GRUNT_1 2
#define LOCALID_MAGMA_HIDEOUT_4F_GRUNT_2 3
#define LOCALID_MAGMA_HIDEOUT_4F_GRUNT_3 4
#define LOCALID_MAGMA_HIDEOUT_4F_TABITHA 5
#define LOCALID_MAGMA_HIDEOUT_4F_MAXIE 6
#define LOCALID_MAGMA_HIDEOUT_4F_GROUDON_SLEEPING 7

// MAP_MARINE_CAVE_END
#define LOCALID_MARINE_CAVE_KYOGRE 1

// MAP_MAUVILLE_CITY
#define LOCALID_MAUVILLE_WALLY 6
#define LOCALID_MAUVILLE_WALLYS_UNCLE 7
#define LOCALID_MAUVILLE_SCOTT 11

// MAP_MAUVILLE_CITY_MART
#define LOCALID_MAUVILLE_MART_CLERK 1

// MAP_MAUVILLE_CITY_POKEMON_CENTER_1F
#define LOCALID_MAUVILLE_NURSE 1

// MAP_METEOR_FALLS_1F_1R
#define LOCALID_METEOR_FALLS_MAGMA_GRUNT_1 5
#define LOCALID_METEOR_FALLS_MAGMA_GRUNT_2 6
#define LOCALID_METEOR_FALLS_ARCHIE 7
#define LOCALID_METEOR_FALLS_AQUA_GRUNT_1 8
#define LOCALID_METEOR_FALLS_AQUA_GRUNT_2 9

// MAP_METEOR_FALLS_STEVENS_CAVE
#define LOCALID_METEOR_FALLS_STEVEN 1

// MAP_MIRAGE_TOWER_4F
#define LOCALID_MIRAGE_ROOT_FOSSIL 1
#define LOCALID_MIRAGE_CLAW_FOSSIL 2

// MAP_MOSSDEEP_CITY
#define LOCALID_MOSSDEEP_GRUNT_1 10
#define LOCALID_MOSSDEEP_GRUNT_2 11
#define LOCALID_MOSSDEEP_GRUNT_3 12
#define LOCALID_MOSSDEEP_GRUNT_4 13
#define LOCALID_MOSSDEEP_MAXIE 14
#define LOCALID_MOSSDEEP_SCOTT 16

// MAP_MOSSDEEP_CITY_HOUSE2
#define LOCALID_MOSSDEEP_HOUSE_WINGULL 3

// MAP_MOSSDEEP_CITY_MART
#define LOCALID_MOSSDEEP_MART_CLERK 1

// MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F
#define LOCALID_MOSSDEEP_NURSE 1

// MAP_MOSSDEEP_CITY_SPACE_CENTER_1F
#define LOCALID_SPACE_CENTER_1F_SCIENTIST_1 1
#define LOCALID_SPACE_CENTER_1F_SCIENTIST_2 2
#define LOCALID_SPACE_CENTER_1F_SAILOR 3
#define LOCALID_SPACE_CENTER_1F_OLD_MAN 4
#define LOCALID_SPACE_CENTER_1F_WOMAN 5
#define LOCALID_SPACE_CENTER_1F_STAIR_GRUNT 9

// MAP_MOSSDEEP_CITY_SPACE_CENTER_2F
#define LOCALID_SPACE_CENTER_2F_RICH_BOY 1
#define LOCALID_SPACE_CENTER_2F_GENTLEMAN 2
#define LOCALID_SPACE_CENTER_2F_SCIENTIST 3
#define LOCALID_SPACE_CENTER_2F_STEVEN 4
#define LOCALID_SPACE_CENTER_GRUNT_6 5
#define LOCALID_SPACE_CENTER_GRUNT_5 6
#define LOCALID_SPACE_CENTER_GRUNT_7 7
#define LOCALID_SPACE_CENTER_TABITHA 8
#define LOCALID_SPACE_CENTER_MAXIE 9

// MAP_MOSSDEEP_CITY_STEVENS_HOUSE
#define LOCALID_STEVENS_HOUSE_STEVEN 1
#define LOCALID_STEVENS_HOUSE_BALL 2

// MAP_MT_CHIMNEY
#define LOCALID_MT_CHIMNEY_ARCHIE 1
#define LOCALID_MT_CHIMNEY_MAXIE 2
#define LOCALID_MT_CHIMNEY_TABITHA 3
#define LOCALID_MT_CHIMNEY_MAGMA_GRUNT_2 22
#define LOCALID_MT_CHIMNEY_MAGMA_GRUNT_1 29

// MAP_MT_CHIMNEY_CABLE_CAR_STATION
#define LOCALID_MT_CHIMNEY_CABLE_CAR_ATTENDANT 1

// MAP_MT_PYRE_SUMMIT
#define LOCALID_MT_PYRE_SUMMIT_ARCHIE 2
#define LOCALID_MT_PYRE_SUMMIT_OLD_LADY 3
#define LOCALID_MT_PYRE_SUMMIT_GRUNT_1 4
#define LOCALID_MT_PYRE_SUMMIT_GRUNT_2 5
#define LOCALID_MT_PYRE_SUMMIT_GRUNT_3 6
#define LOCALID_MT_PYRE_SUMMIT_GRUNT_4 7
#define LOCALID_MT_PYRE_SUMMIT_MAXIE 8

// MAP_NAVEL_ROCK_BOTTOM
#define LOCALID_NAVEL_ROCK_LUGIA 1

// MAP_NAVEL_ROCK_HARBOR
#define LOCALID_NAVEL_ROCK_SAILOR 1
#define LOCALID_NAVEL_ROCK_SS_TIDAL 2

// MAP_NAVEL_ROCK_TOP
#define LOCALID_NAVEL_ROCK_HO_OH 1

// MAP_OLDALE_TOWN
#define LOCALID_OLDALE_MART_EMPLOYEE 2
#define LOCALID_FOOTPRINTS_MAN 3
#define LOCALID_OLDALE_RIVAL 4

// MAP_OLDALE_TOWN_MART
#define LOCALID_OLDALE_MART_CLERK 1

// MAP_OLDALE_TOWN_POKEMON_CENTER_1F
#define LOCALID_OLDALE_NURSE 1

// MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F
#define LOCALID_PACIFIDLOG_NURSE 1

// MAP_PETALBURG_CITY
#define LOCALID_PETALBURG_WALLY 2
#define LOCALID_PETALBURG_BOY 3
#define LOCALID_PETALBURG_WALLYS_DAD 5
#define LOCALID_GYM_BOY 8
#define LOCALID_PETALBURG_SCOTT 9

// MAP_PETALBURG_CITY_GYM
#define LOCALID_PETALBURG_GYM_NORMAN 1
#define LOCALID_PETALBURG_GYM_WALLY 10
#define LOCALID_PETALBURG_GYM_WALLYS_DAD 11

// MAP_PETALBURG_CITY_MART
#define LOCALID_PETALBURG_MART_CLERK 1

// MAP_PETALBURG_CITY_POKEMON_CENTER_1F
#define LOCALID_PETALBURG_NURSE 1

// MAP_PETALBURG_CITY_WALLYS_HOUSE
#define LOCALID_WALLYS_HOUSE_WALLYS_DAD 1

// MAP_PETALBURG_WOODS
#define LOCALID_PETALBURG_WOODS_GRUNT 3
#define LOCALID_PETALBURG_WOODS_DEVON_EMPLOYEE 4

// MAP_POHUTU_CITY_2
#define LOCALID_POHUTU_DAD 1
#define LOCALID_POHUTU_BOAT 2

// MAP_ROUTE101
#define LOCALID_ROUTE101_BIRCH 2
#define LOCALID_ROUTE101_ZIGZAGOON 4

// MAP_ROUTE103
#define LOCALID_ROUTE103_RIVAL 2

// MAP_ROUTE104
#define LOCALID_ROUTE104_BOAT 7
#define LOCALID_ROUTE104_BRINEY 8
#define LOCALID_ROUTE104_RIVAL 34

// MAP_ROUTE104_MR_BRINEYS_HOUSE
#define LOCALID_BRINEYS_HOUSE_BRINEY 1
#define LOCALID_BRINEYS_HOUSE_PEEKO 2

// MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP
#define LOCALID_FLOWER_SHOP_OWNER 1

// MAP_ROUTE109
#define LOCALID_ROUTE109_BOAT 1
#define LOCALID_ROUTE109_BRINEY 2

// MAP_ROUTE110
#define LOCALID_CHALLENGE_BIKER 21
#define LOCALID_ROUTE110_RIVAL 28
#define LOCALID_ROUTE110_RIVAL_ON_BIKE 29
#define LOCALID_ROUTE110_BIRCH 36

// MAP_ROUTE110_TRICK_HOUSE_END
#define LOCALID_TRICK_MASTER_END 1

// MAP_ROUTE110_TRICK_HOUSE_ENTRANCE
#define LOCALID_TRICK_MASTER 1

// MAP_ROUTE110_TRICK_HOUSE_PUZZLE5
#define LOCALID_MECHADOLL_1 1
#define LOCALID_MECHADOLL_2 2
#define LOCALID_MECHADOLL_3 3
#define LOCALID_MECHADOLL_4 4
#define LOCALID_MECHADOLL_5 5

// MAP_ROUTE111
#define LOCALID_ROUTE111_VICTOR 1
#define LOCALID_ROUTE111_VICTORIA 2
#define LOCALID_ROUTE111_VIVI 3
#define LOCALID_ROUTE111_VICKY 4
#define LOCALID_ROUTE111_TY_1 13
#define LOCALID_ROUTE111_GABBY_1 14
#define LOCALID_ROUTE111_GABBY_2 21
#define LOCALID_ROUTE111_TY_2 22
#define LOCALID_ROUTE111_GABBY_3 23
#define LOCALID_ROUTE111_TY_3 24
#define LOCALID_ROUTE111_PLAYER_FALLING 45
#define LOCALID_ROUTE111_ROCK_SMASH_MAN 46

// MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE
#define LOCALID_WINSTRATE_HOUSE_VIVI 1
#define LOCALID_WINSTRATE_HOUSE_VICTOR 2
#define LOCALID_WINSTRATE_HOUSE_VICTORIA 3
#define LOCALID_WINSTRATE_HOUSE_VICKY 4

// MAP_ROUTE112
#define LOCALID_ROUTE112_GRUNT_1 1
#define LOCALID_ROUTE112_GRUNT_2 6

// MAP_ROUTE112_CABLE_CAR_STATION
#define LOCALID_ROUTE112_CABLE_CAR_ATTENDANT 1

// MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL
#define LOCALID_FOSSIL_MANIAC 1

// MAP_ROUTE116
#define LOCALID_ROUTE116_BRINEY 11
#define LOCALID_ROUTE116_WANDAS_BF 21

// MAP_ROUTE117
#define LOCALID_DAYCARE_MAN 3

// MAP_ROUTE117_POKEMON_DAY_CARE
#define LOCALID_DAYCARE_LADY 1

// MAP_ROUTE118
#define LOCALID_ROUTE118_GABBY_1 5
#define LOCALID_ROUTE118_TY_1 6
#define LOCALID_ROUTE118_GABBY_2 8
#define LOCALID_ROUTE118_TY_2 9
#define LOCALID_ROUTE118_GABBY_3 10
#define LOCALID_ROUTE118_TY_3 11
#define LOCALID_ROUTE118_STEVEN 19

// MAP_ROUTE119
#define LOCALID_ROUTE119_RIVAL 16
#define LOCALID_ROUTE119_RIVAL_ON_BIKE 25
#define LOCALID_ROUTE119_SCOTT 43

// MAP_ROUTE119_WEATHER_INSTITUTE_1F
#define LOCALID_WEATHER_INSTITUTE_LITTLE_BOY 5

// MAP_ROUTE119_WEATHER_INSTITUTE_2F
#define LOCALID_WEATHER_INSTITUTE_2F_GRUNT_1 1
#define LOCALID_WEATHER_INSTITUTE_2F_GRUNT_2 2
#define LOCALID_WEATHER_INSTITUTE_2F_SHELLY 3
#define LOCALID_WEATHER_INSTITUTE_2F_SCIENTIST 5
#define LOCALID_WEATHER_INSTITUTE_2F_GRUNT_3 7
#define LOCALID_WEATHER_INSTITUTE_2F_GRUNT_4 8

// MAP_ROUTE120
#define LOCALID_ROUTE120_TY_1 17
#define LOCALID_ROUTE120_GABBY_1 18
#define LOCALID_ROUTE120_GABBY_2 19
#define LOCALID_ROUTE120_TY_2 20
#define LOCALID_BRIDGE_KECLEON 30
#define LOCALID_ROUTE120_STEVEN 31
#define LOCALID_BRIDGE_KECLEON_SHADOW 36

// MAP_ROUTE121
#define LOCALID_ROUTE121_GRUNT_1 12
#define LOCALID_ROUTE121_GRUNT_2 13
#define LOCALID_ROUTE121_GRUNT_3 14

// MAP_ROUTE128
#define LOCALID_ROUTE128_STEVEN 3
#define LOCALID_ROUTE128_ARCHIE 4
#define LOCALID_ROUTE128_MAXIE 5

// MAP_ROUTE23
#define LOCALID_ROUTE23_BOAT 1
#define LOCALID_ROUTE23_DAD 2

// MAP_RUSTBORO_CITY
#define LOCALID_RUSTBORO_LITTLE_BOY 7
#define LOCALID_RUSTBORO_LITTLE_GIRL 8
#define LOCALID_RUSTBORO_DEVON_EMPLOYEE 9
#define LOCALID_RUSTBORO_GRUNT 10
#define LOCALID_RUSTBORO_RIVAL 14
#define LOCALID_RUSTBORO_SCIENTIST 15

// MAP_RUSTBORO_CITY_DEVON_CORP_1F
#define LOCALID_DEVON_CORP_STAIR_GUARD 2

// MAP_RUSTBORO_CITY_DEVON_CORP_2F
#define LOCALID_FOSSIL_SCIENTIST 5

// MAP_RUSTBORO_CITY_DEVON_CORP_3F
#define LOCALID_DEVON_CORP_3F_EMPLOYEE 2

// MAP_RUSTBORO_CITY_FLAT1_2F
#define LOCALID_WALDAS_DAD 6

// MAP_RUSTBORO_CITY_MART
#define LOCALID_RUSTBORO_MART_CLERK 1

// MAP_RUSTBORO_CITY_POKEMON_CENTER_1F
#define LOCALID_RUSTBORO_NURSE 1

// MAP_RUSTURF_TUNNEL
#define LOCALID_RUSTURF_TUNNEL_WANDAS_BF 1
#define LOCALID_RUSTURF_TUNNEL_BRINEY 5
#define LOCALID_RUSTURF_TUNNEL_GRUNT 6
#define LOCALID_RUSTURF_TUNNEL_PEEKO 7
#define LOCALID_RUSTURF_TUNNEL_WANDA 10

// MAP_SS_TIDAL_CORRIDOR
#define LOCALID_SS_TIDAL_EXIT_SAILOR 1
#define LOCALID_SS_TIDAL_SCOTT 5

// MAP_SAFARI_ZONE_SOUTH
#define LOCALID_SAFARI_EXIT_ATTENDANT 1

// MAP_SEAFLOOR_CAVERN_ENTRANCE
#define LOCALID_SEAFLOOR_CAVERN_ENTRANCE_GRUNT 1

// MAP_SEAFLOOR_CAVERN_ROOM9
#define LOCALID_SEAFLOOR_CAVERN_KYOGRE 1
#define LOCALID_SEAFLOOR_CAVERN_ARCHIE 2
#define LOCALID_SEAFLOOR_CAVERN_MAXIE 3
#define LOCALID_SEAFLOOR_CAVERN_GRUNT_1 4
#define LOCALID_SEAFLOOR_CAVERN_GRUNT_2 5
#define LOCALID_SEAFLOOR_CAVERN_KYOGRE_SLEEPING 7

// MAP_SKY_PILLAR_OUTSIDE
#define LOCALID_SKY_PILLAR_WALLACE 1

// MAP_SKY_PILLAR_TOP
#define LOCALID_RAYQUAZA_SLEEPING 1

// MAP_SLATEPORT_CITY
#define LOCALID_SLATEPORT_FAT_MAN 1
#define LOCALID_SLATEPORT_MAN_1 2
#define LOCALID_SLATEPORT_RICH_BOY 3
#define LOCALID_SLATEPORT_GRUNT_1 5
#define LOCALID_SLATEPORT_COOK 6
#define LOCALID_SLATEPORT_OLD_WOMAN 7
#define LOCALID_SLATEPORT_GIRL 8
#define LOCALID_SLATEPORT_TY 9
#define LOCALID_SLATEPORT_GABBY 10
#define LOCALID_SLATEPORT_CAPT_STERN 11
#define LOCALID_SLATEPORT_GRUNT_2 18
#define LOCALID_SLATEPORT_GRUNT_3 19
#define LOCALID_SLATEPORT_ENERGY_GURU 25
#define LOCALID_SLATEPORT_GRUNT_4 26
#define LOCALID_SLATEPORT_GRUNT_5 27
#define LOCALID_SLATEPORT_GRUNT_6 28
#define LOCALID_SLATEPORT_GRUNT_7 29
#define LOCALID_SLATEPORT_GRUNT_8 30
#define LOCALID_SLATEPORT_GRUNT_9 31
#define LOCALID_SLATEPORT_GRUNT_11 33
#define LOCALID_SLATEPORT_SCOTT 35

// MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM
#define LOCALID_SLATEPORT_TENT_BATTLE_OPPONENT 2
#define LOCALID_SLATEPORT_TENT_BATTLE_PLAYER 3

// MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR
#define LOCALID_SLATEPORT_TENT_CORRIDOR_ATTENDANT 1

// MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY
#define LOCALID_SLATEPORT_TENT_ATTENDANT 1

// MAP_SLATEPORT_CITY_HARBOR
#define LOCALID_SLATEPORT_HARBOR_CAPT_STERN 4
#define LOCALID_SLATEPORT_HARBOR_SS_TIDAL 5
#define LOCALID_SLATEPORT_HARBOR_GRUNT 6
#define LOCALID_SLATEPORT_HARBOR_ARCHIE 7
#define LOCALID_SLATEPORT_HARBOR_SUBMARINE 8

// MAP_SLATEPORT_CITY_MART
#define LOCALID_SLATEPORT_MART_CLERK 1

// MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F
#define LOCALID_OCEANIC_MUSEUM_FAMILIAR_GRUNT 13

// MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F
#define LOCALID_OCEANIC_MUSEUM_2F_CAPT_STERN 1
#define LOCALID_OCEANIC_MUSEUM_2F_ARCHIE 2
#define LOCALID_OCEANIC_MUSEUM_2F_GRUNT_1 3
#define LOCALID_OCEANIC_MUSEUM_2F_GRUNT_2 4

// MAP_SLATEPORT_CITY_POKEMON_CENTER_1F
#define LOCALID_SLATEPORT_NURSE 1

// MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F
#define LOCALID_DOCK 1

// MAP_SOOTOPOLIS_CITY
#define LOCALID_SOOTOPOLIS_EXPERT 1
#define LOCALID_SOOTOPOLIS_WOMAN_2 2
#define LOCALID_KIRI 3
#define LOCALID_SOOTOPOLIS_NINJA_BOY 4
#define LOCALID_SOOTOPOLIS_BOY_1 5
#define LOCALID_SOOTOPOLIS_STEVEN 7
#define LOCALID_SOOTOPOLIS_WOMAN_1 8
#define LOCALID_SOOTOPOLIS_GROUDON 9
#define LOCALID_SOOTOPOLIS_KYOGRE 10
#define LOCALID_SOOTOPOLIS_RAYQUAZA 11
#define LOCALID_SOOTOPOLIS_MANIAC 12
#define LOCALID_SOOTOPOLIS_GIRL 13
#define LOCALID_SOOTOPOLIS_BLACK_BELT 14
#define LOCALID_SOOTOPOLIS_BOY_2 15
#define LOCALID_SOOTOPOLIS_MAXIE 16
#define LOCALID_SOOTOPOLIS_ARCHIE 17
#define LOCALID_SOOTOPOLIS_WALLACE 18

// MAP_SOOTOPOLIS_CITY_MART
#define LOCALID_SOOTOPOLIS_MART_CLERK 1

// MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F
#define LOCALID_MYSTERY_EVENTS_OLD_MAN 1

// MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F
#define LOCALID_SOOTOPOLIS_NURSE 1

// MAP_SOUTHERN_ISLAND_EXTERIOR
#define LOCALID_SOUTHERN_ISLAND_SAILOR 1
#define LOCALID_SOUTHERN_ISLAND_SS_TIDAL 2

// MAP_SOUTHERN_ISLAND_INTERIOR
#define LOCALID_SOUTHERN_ISLAND_LATI 2

// MAP_TERRA_CAVE_END
#define LOCALID_TERRA_CAVE_GROUDON 1

// MAP_TRAINER_HILL_ELEVATOR
#define LOCALID_TRAINER_HILL_ELEVATOR_ATTENDANT 1

// MAP_TRAINER_HILL_ENTRANCE
#define LOCALID_TRAINER_HILL_ATTENDANT 1
#define LOCALID_TRAINER_HILL_NURSE 2
#define LOCALID_TRAINER_HILL_GIRL 4
#define LOCALID_TRAINER_HILL_MAN 5

// MAP_UNION_ROOM
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9

// MAP_VERDANTURF_TOWN
#define LOCALID_VERDANTURF_TWIN 2

// MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM
#define LOCALID_VERDANTURF_TENT_BATTLE_PLAYER 1
#define LOCALID_VERDANTURF_TENT_BATTLE_OPPONENT 2
#define LOCALID_VERDANTURF_TENT_BATTLE_ATTENDANT 3

// MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR
#define LOCALID_VERDANTURF_TENT_CORRIDOR_ATTENDANT 1

// MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY
#define LOCALID_VERDANTURF_TENT_ATTENDANT 1

// MAP_VERDANTURF_TOWN_MART
#define LOCALID_VERDANTURF_MART_CLERK 1

// MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F
#define LOCALID_VERDANTURF_NURSE 1

// MAP_VICTORY_ROAD_1F
#define LOCALID_VICTORY_ROAD_ENTRANCE_WALLY 4

#endif // GUARD_CONSTANTS_MAP_EVENT_IDS_H
